export enum AISuggestionType {
  PROBLEMATIQUE = 'PROBLEMATIQUE',
  OBJECTIF = 'OBJECTIF',
  AXE = 'AXE',
  HYPOTHESE = 'HYPOTHESE',
  QUESTION = 'QUESTION',
  KEYWORD = 'KEYWORD',
  SOURCE = 'SOURCE',
  PERIMETER = 'PERIMETER',
}
