export enum InsightType {
  OPPORTUNITY = 'OPPORTUNITY',
  THREAT = 'THREAT',
  TREND = 'TREND',
  SIGNAL_FAIBLE = 'SIGNAL_FAIBLE',
  CONFIRMATION = 'CONFIRMATION',
  ALERT = 'ALERT',
  INFORMATION = 'INFORMATION',
}
