export enum VeilleType {
  TECHNOLOGIQUE = 'TECHNOLOGIQUE',
  CONCURRENTIELLE = 'CONCURRENTIELLE',
  COMMERCIALE = 'COMMERCIALE',
  REGLEMENTAIRE = 'REGLEMENTAIRE',
  STRATEGIQUE = 'STRATEGIQUE',
  E_REPUTATION = 'E_REPUTATION',
  SCIENTIFIQUE = 'SCIENTIFIQUE',
  GEOPOLITIQUE = 'GEOPOLITIQUE',
  ENVIRONNEMENTALE = 'ENVIRONNEMENTALE',
  SECURITAIRE = 'SECURITAIRE',
  SOCIETALE = 'SOCIETALE',
  CUSTOM = 'CUSTOM',
}
