export enum VeilleType {
  TECHNOLOGIQUE = 'TECHNOLOGIQUE',
  CONCURRENTIELLE = 'CONCURRENTIELLE',
  REGLEMENTAIRE = 'REGLEMENTAIRE',
  MARCHES = 'MARCHES',
  SCIENTIFIQUE = 'SCIENTIFIQUE',
  MEDIAS = 'MEDIAS',
  CUSTOM = 'CUSTOM',
}
